"""empty message

Revision ID: 43729577f6cd
Revises: ed70045f23f2
Create Date: 2021-02-09 15:05:34.726488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43729577f6cd'
down_revision = 'ed70045f23f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('produto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('preço', sa.Integer(), nullable=True),
    sa.Column('estoque', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('estoque'),
    sa.UniqueConstraint('nome'),
    sa.UniqueConstraint('preço')
    )
    op.drop_table('aluno')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aluno',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nome', sa.VARCHAR(length=50), nullable=False),
    sa.Column('dre', sa.INTEGER(), nullable=True),
    sa.Column('cpf', sa.INTEGER(), nullable=True),
    sa.Column('dataNascimento', sa.VARCHAR(length=8), nullable=False),
    sa.Column('sexo', sa.VARCHAR(length=10), nullable=False),
    sa.Column('periodoIngresso', sa.INTEGER(), nullable=True),
    sa.Column('curso', sa.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('dre')
    )
    op.drop_table('produto')
    # ### end Alembic commands ###
