"""empty message

Revision ID: 529a97a43282
Revises: 
Create Date: 2021-02-11 15:02:23.678697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '529a97a43282'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('produto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('preço', sa.Float(), nullable=True),
    sa.Column('estoque', sa.Integer(), nullable=True),
    sa.Column('descrição', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=40), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('cidade', sa.Text(), nullable=False),
    sa.Column('cep', sa.Integer(), nullable=True),
    sa.Column('endereço', sa.Text(), nullable=False),
    sa.Column('bloco_apartamento', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('produto')
    # ### end Alembic commands ###
