"""empty message

Revision ID: ed70045f23f2
Revises: dfa51f885702
Create Date: 2021-02-09 14:30:27.105009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed70045f23f2'
down_revision = 'dfa51f885702'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('association')
    op.drop_table('materia')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('materia',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nome', sa.VARCHAR(length=50), nullable=False),
    sa.Column('codigo', sa.VARCHAR(length=15), nullable=False),
    sa.Column('creditos', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('association',
    sa.Column('materia_id', sa.INTEGER(), nullable=True),
    sa.Column('aluno_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['aluno_id'], ['aluno.id'], ),
    sa.ForeignKeyConstraint(['materia_id'], ['materia.id'], )
    )
    # ### end Alembic commands ###
